Documentation for extending mc docker image with additional configuration
hazelcast/management-center-docker pull request #40
Opened 2020-10-01 09:18 UTC by alex-dukhno

* add docs for extending mc docker image with additional configuration
* add table of content

2020-10-01 13:15 UTC, alex-dukhno commented
related to #25

2020-10-01 13:26 UTC, erosb requested changes
Thank you @alex-dukhno , I added 2 comments.

2020-10-01 13:26 UTC, erosb commented on README.md
> +[Quick Start]: #quick-start
Not closely related to this PR, but if you are working on the docs anyway, please add a note in bold that users shouldn't use the `:latest` tag, since they can't know if the most recent release was 3.x or 4.x. So they should explicitly set the version number, according to their IMDG major version.

2020-10-01 13:26 UTC, erosb commented on README.md
> +If you are creating Docker imange with `hazelcast/management-center` as a base image and want to make additional configuration using `mc-conf.sh` you have to specify `--home=${MC_DATA}` flag for each
Please write it as "If you create a Docker image". At least change "imange" to "image" :)

Where does this $MC_DATA environment variable come from? Is it always defined in an MC container? As a reader I would like to know what this is. Can `$MC_DATA` contain whitespaces, by any chance? If yes, then it is safer to use `--host="${MC_DATA}"` .

Nit: can we please use "directory" instead of "folder"? Directory is just more common in linux terminology.

2020-10-01 14:04 UTC, alex-dukhno commented on README.md
> +[Quick Start]: #quick-start
added in https://github.com/hazelcast/management-center-docker/pull/40/commits/9170724b9e3694dc9fa6d8ddd14d687dcf96c93e

2020-10-01 14:04 UTC, alex-dukhno commented on README.md
> +If you are creating Docker imange with `hazelcast/management-center` as a base image and want to make additional configuration using `mc-conf.sh` you have to specify `--home=${MC_DATA}` flag for each
updated in https://github.com/hazelcast/management-center-docker/pull/40/commits/9170724b9e3694dc9fa6d8ddd14d687dcf96c93e

2020-10-01 16:02 UTC, erosb commented on README.md
> +      && /mc-start.sh \
oops and this is `./mc-start.sh` , (mind the `.`)

2020-10-01 16:15 UTC, yuraku commented on README.md
> +[Quick Start]: #quick-start
`latest` can be only 4.x as we have only one project on the hub. For example for OpenShift images, we have separate project for 3.x and 4.x so there are two `latest` to tags

2020-10-01 16:25 UTC, alex-dukhno commented on README.md
> +      && /mc-start.sh \
I've double checked and `./mc-start.sh` fails with `bash: ./mc-start.sh: No such file or directory`

2020-10-01 16:26 UTC, alex-dukhno commented on README.md
> +      && ./mc-conf.sh cluster add --cluster-name=${MC_CLUSTER1_NAME} --member-addresses=${MC_CLUSTER1_ADDRESSLIST} --home=${MC_DATA} \
addressed https://github.com/hazelcast/management-center-docker/pull/40/commits/af00a4dca598826d179fc30bcc24c2ce59189741

2020-10-01 16:29 UTC, erosb commented on README.md
> +[Quick Start]: #quick-start
@yuraku [right now](https://hub.docker.com/r/hazelcast/management-center/tags) `:latest` was released 23 days ago, and `.3.12.12` was also released 23 days ago. Aren't they the same?

2020-10-01 16:30 UTC, yuraku commented on README.md
> +[Quick Start]: #quick-start
no, it's `ENV MC_VERSION=4.2020.08`

2020-10-01 16:31 UTC, yuraku commented on README.md
> +[Quick Start]: #quick-start
3.12.12 updated the latest by mistake, so I've fixed it and published the correct one, that's why it's on the same date

2020-10-01 16:32 UTC, erosb commented on README.md
> +      && /mc-start.sh \
Right, pardon me. I can't see why do we handle the mc-start.sh separately from the rest of the package but nevermind.

2020-10-01 17:00 UTC, alex-dukhno commented on README.md
> +      && /mc-start.sh \
🤷‍♂️

2020-10-02 08:27 UTC, alex-dukhno commented on README.md
> +[Quick Start]: #quick-start
anyway, I think it is a good practice to use concrete tags and encourage users to do so, at least can save time during debugging

2020-10-02 08:29 UTC, yuraku commented on README.md
> +[Quick Start]: #quick-start
totally agree. just saying that we shouldn't specify anywhere that we have two `latest` tags

2020-10-05 08:46 UTC, erosb approved these changes

2020-10-05 08:52 UTC, emre-aydin commented on README.md
> + - [Configuring management center inside you custome Docker image]
```suggestion
 - [Configuring Management Center inside your custom Docker image]
```

2020-10-05 08:52 UTC, emre-aydin commented on README.md
> +**NOTE:** Please, make sure that you are not using `:latest` tag, because 3.x and 4.x versions are not compatible. You can check [Supported Environments](https://docs.hazelcast.org/docs/management-ce
```suggestion
**NOTE:** Please, make sure that you are not using `latest` tag, because 3.x and 4.x versions are not compatible. You can check [Supported Environments](https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html#supported-environments) section for more info on compatibility versions between Management Center and IMDG, Jet clusters.
```

2020-10-05 08:54 UTC, emre-aydin commented on README.md
>  ## Customizing container setup
```suggestion
## Customizing Container Setup
```

2020-10-05 08:54 UTC, emre-aydin commented on README.md
> +[Customizing container setup]: #customizing-container-setup
```suggestion
[Customizing Container Setup]: #customizing-container-setup
```

2020-10-05 08:55 UTC, emre-aydin commented on README.md
> +## Configuring management center inside you custome Docker image
```suggestion
## Configuring Management Center Inside Your Custom Docker Image
```

2020-10-05 08:55 UTC, emre-aydin commented on README.md
> +If you create Docker image with `hazelcast/management-center` as a base image and want to make additional configuration using `mc-conf.sh` you have to specify `--home="${MC_DATA}"` flag for each `mc-
```suggestion
If you create Docker image with `hazelcast/management-center` as a base image and want to make additional configuration using `mc-conf.sh`, you have to specify `--home="${MC_DATA}"` flag for each `mc-conf` command. That makes sure that `mc-conf` stores data to the same directory that Management Center will use at runtime.
```

2020-10-05 08:56 UTC, emre-aydin commented on README.md
> +**NOTE:** `$MC_DATA` env variable is coming from `hazelcast/management-center` and used to save the configuration and other needed data during Management Center running time
```suggestion
**NOTE:** `$MC_DATA` env variable is coming from `hazelcast/management-center`. It is used to save the configuration and other needed data when running Management Center.
```

2020-10-05 08:57 UTC, emre-aydin commented on README.md
> +[Configuring management center inside you custome Docker image]: #configuring-management-center-inside-you-custome-docker-image
```suggestion
[Configuring Management Center Inside Your Custom Docker Image]: #configuring-management-center-inside-you-custome-docker-image
```

2020-10-05 08:58 UTC, emre-aydin commented on README.md
> +[Start with a preconfigured admin user]: #start-with-a-preconfigured-admin-user
```suggestion
[Start with a Preconfigured Admin User]: #start-with-a-preconfigured-admin-user
```

2020-10-05 09:04 UTC, emre-aydin commented on README.md
>  ## Start with a preconfigured admin user
```suggestion
## Start with a Preconfigured Admin User
```

2020-10-05 09:04 UTC, emre-aydin commented on README.md
>  ## JVM heap configuration
```suggestion
## JVM Heap Configuration
```

2020-10-05 09:04 UTC, emre-aydin commented on README.md
> +[JVM heap configuration]: #jvm-heap-configuration
```suggestion
[JVM Heap Configuration]: #jvm-heap-configuration
```

2020-10-05 09:05 UTC, emre-aydin commented on README.md
> + - [Customizing container setup]
```suggestion
 - [Customizing Container Setup]
```

2020-10-05 09:05 UTC, emre-aydin commented on README.md
> + - [Start with a preconfigured admin user]
```suggestion
 - [Start with a Preconfigured Admin User]
```

2020-10-05 09:06 UTC, emre-aydin commented on README.md
> + - [JVM heap configuration]
```suggestion
 - [JVM Heap Configuration]
```

2020-10-05 09:25 UTC, emre-aydin approved these changes

2020-10-05 09:43 UTC, merged