Changed base image in Dockerfile and other updates
hazelcast/management-center-docker pull request #74
Opened 2021-02-23 01:05 UTC by yuraku

1. Changed base image from Apline to OpenShift
2. Added removed before platforms that were failing during the build
3. Added additional security scan tools
4. Added e2e UI tests as part of Docker image release

2021-02-23 09:24 UTC, emre-aydin commented on .github/containerscan/allowedlist.yaml
> +  # netty-tcnative still requires libssl 1.0
What are these commented out sections for?

2021-02-23 09:26 UTC, emre-aydin commented
It might be a good idea to mention the JIRA issue in the PR title so that the PR is associated with the correct JIRA issue.

2021-02-23 09:28 UTC, emre-aydin commented on .github/workflows/tag_image_push.yml
> +      - name: Scan Hazelcast Management Center image by Azure (Trivy + Dockle)
Does it mean that we do these scans after the image is published? I think we should first do the checks and fail the publish job if any of them fails.

2021-02-23 09:29 UTC, yuraku commented on .github/containerscan/allowedlist.yaml
> +  # netty-tcnative still requires libssl 1.0
The issues are related to IMDG product, for now just left it as a template

2021-02-23 09:29 UTC, emre-aydin commented on .github/workflows/vulnerability_scan.yml
> +        if: always()
How are we notified if any of these scans fail?

2021-02-23 09:43 UTC, yuraku commented on .github/workflows/vulnerability_scan.yml
> +        if: always()
so far we're not notified, it will fail the job (so for now we should just monitor the job progress)

2021-02-23 09:51 UTC, yuraku commented
> It might be a good idea to mention the JIRA issue in the PR title so that the PR is associated with the correct JIRA issue.

added 👍🏻

2021-02-23 09:57 UTC, emre-aydin commented on Dockerfile
> +      maintainer="info@hazelcast.com" \
we can use `management-center@hazelcast.com`

2021-02-23 09:59 UTC, emre-aydin commented
Did you check whether the commands in the README still work after your changes (for e.g. for adding users etc.)?
Also, did you check whether this image is extendable as described in the README?

2021-02-23 10:00 UTC, emre-aydin commented on .github/workflows/vulnerability_scan.yml
> +        if: always()
does github actions automatically notify when an action fails? if not, we should add email notification, otherwise these will go unnoticed.

2021-02-23 12:14 UTC, yuraku commented on .github/workflows/vulnerability_scan.yml
> +        if: always()
it sends email automatically

2021-02-23 12:50 UTC, yuraku reviewed
> Did you check whether the commands in the README still work after your changes (for e.g. for adding users etc.)?
> Also, did you check whether this image is extendable as described in the README?

Yes, and by this updated the README due to changes in conf scripts path changes

2021-02-23 12:50 UTC, yuraku commented on Dockerfile
> +      maintainer="info@hazelcast.com" \
updated

2021-02-23 12:50 UTC, yuraku commented on .github/workflows/tag_image_push.yml
> +      - name: Scan Hazelcast Management Center image by Azure (Trivy + Dockle)
I've checked the file again, and it's possible to scan local images, but the problem is that we're building and pushing images in scope of one action:
```
docker buildx build --push \
        ${TAGS} \
        --platform=linux/arm64,linux/amd64,linux/ppc64le,linux/s390x .
```

2021-02-23 13:28 UTC, emre-aydin approved these changes

2021-02-24 09:04 UTC, hasancelik commented on .github/workflows/tag_image_push.yml
> +      - name: Scan Hazelcast Management Center image by Azure (Trivy + Dockle)
Most of the time, scan builds fail/are red because reported vulnerabilities usually come from third party libraries and base image itself and whitelist is not avaliable for some scan tools like anchore/grype. That's why release pipeline will be blocked by scan steps always. I think release actions should not check vulnerabilities, daily and push actions are enough for detecting them. Probably, we will remove them from IMDG docker actions in near future.

2021-02-24 10:06 UTC, hasancelik requested changes
@yuraku Did you test this version of image at RedHat connect via manual push?

2021-02-24 10:06 UTC, hasancelik commented on Dockerfile
> +      release="${MC_VERSION}" \
`release` label is not related to MC version itself. "_It is a number used to identify the specific build for this image_". You can find all detailed infos about certification requirements [here](https://connect.redhat.com/zones/containers/container-certification-policy-guide).

2021-03-25 07:14 UTC, emre-aydin commented on Dockerfile
> +FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3
AFAIU there are some hesitations on switching to UBI for our Docker images. @hasancelik recently mentioned RedHat is sometimes slow to upgrade their dependencies with regards to security vulnerabilities. Last I checked, it was still being discussed. What's the current decision @hasancelik? Should we switch to UBI or stay with Alpine?

2021-03-25 09:24 UTC, hasancelik commented on Dockerfile
> +FROM registry.access.redhat.com/ubi8/ubi-minimal:8.3
> slow to upgrade their dependencies with regards to security vulnerabilities.

As I mentioned before at related slack thread, it is just my observation, they are just a little bit slow to classify CVEs or provide description for them. Probably, they have some internal bureaucracy to verify and fixed them. For the alpine, if someone discovers vulnerability at linux library that is used by alpine, community force its maintainers to fix.

We did not make any decision about reverting base OS image at IMDG side, we will continue with UBI one for now.

2021-12-14 20:49 UTC, closed without merging